name: Build Tailwind CSS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'assets/css/*.css'
      - 'assets/css/*.css.map'

  pull_request:
    branches:
      - main
    paths:
      - 'assets/css/**'
      - '**/*.php'
      - '**/*.js'
      - '**/*.html'
      - '**/*.twig'
      - 'tailwind.config.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build Tailwind
        run: npm run build:css

      - name: Commit generated CSS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add assets/css/app.css assets/css/app.css.map assets/css/app.min.css
          git commit -m "build: tailwind css [skip ci]" || echo "No changes"
          git push
